# **Numpy and Image Basics**

When we actually read in image data, the computer is going to read it in as an array.
Let's import Numpy now

In [1]:
import numpy as np  

In [2]:
my_list=[1,2,3]
type(my_list)

list

In [3]:
myarray=np.array(my_list)
myarray
type(myarray)

numpy.ndarray

First method: arange()
Generates an array using given parameters.
To read what a method does just call the method (say np.arange()) and press Shift + Tab

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

It generates an array as arange(start, stop, step)
The last element is one less than the stop index.

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(shape=(10,5)) #rows * columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.zeros() takes shape, dtype (data type), and order as arguments.
It generates zeros according to the dimension specified inside a tuple.
Default data type is float.

In [7]:
type(0.)

float

In [8]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

The above function does the same thing as zeros. 
You can even declare the shape without writing shape. 

In [10]:
np.ones((1,3))

array([[1., 1., 1.]])

In [12]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

randint() method of random class takes start, end and number of numbers to be generated as parameters.

A random seed is a number (or vector) used to initialize a pseudorandom number generator. So whenever you'll write seed as 101 and if the range and number of numbers to be generated is same, you'll get the same result always.

In [15]:
arr2=np.random.randint(0,100,10)
arr2

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [16]:
arr.max()


95

In [17]:
arr.argmax()

0

max() returns highest value in the array and argmax() returns the index of that element in the array.

In [18]:
arr2.min()

0

In [19]:
arr2.argmin()

3

In [20]:
arr.mean()

60.8

In [25]:
arr.shape #shape is not a function it is a tuple so () is not required

(10,)

In [26]:
arr.reshape((2,5)) #as long as number of elements remain same
#if new dimension is not equal to number of elements of the array, error will be shown


array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [27]:
mat = np.arange(0,100).reshape(10,10)

In the above code arange() generates 100 numbers and reshape() arranges the generated range into a 10x10 matrix.
Let's access a particular element from the matrix.

In [28]:
mat[0,1] #row, column

1

In [29]:
mat[4,6]

46

In [30]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

We've used slicing above the get the 1st column of the matrix


In [33]:
#to get the above column in column shape, reshape
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [34]:
#to get a row:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

The above code says grab 0-3 rows and inside those rows, grab only 0:3 columns.

In [39]:
newmat=mat.copy()
mat[0:2,0:2]=0

In [40]:
mat

array([[ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
newmat

array([[ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# What is an image?

* An image is an array, or a matrix, of square pixels (picture elements) arranged in columns and rows.

* In a (8-bit) greyscale image each picture element has an assigned intensity that ranges from *0 to 255*. A grey scale image is what people normally call a black and white image, but the name emphasizes that such an image will also include many shades of grey.



* Colour images can be represented as a combination of Red, Green and Blue.
Additive colour mixing allows us to represent a wide variety of colours by simply combining different amount of RGB.
Each colour channel will have intensity values. 

* When you read a colour image it has three dimensions, Height, Width and Color Channels.
This means when you read in an image and check its shape, it will look like (1280,720,3)--> 1280x720 = Resolution, 3 colour channels


* Computer won't "know" a channel is Red, it just knows that there are now 3 intensity channels.
The user needs to dictate which channel is which colour. Each channel alone is essentially the same as a greyscale image.